on: push
name: Publish on Netlify

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Publish
        uses: netlify/actions/build@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NETLIFY_SITE_ID: 7159b05c-3cc0-429f-9cb9-ee4794056c0d
